import { IDiscordGuild } from '../../common/types';
import DiscordClient from '../../DiscordClient';
import ChannelStore from '../../stores/ChannelStore';
import EmojiStore from '../../stores/EmojiStore';
import GuildMemberStore from '../../stores/GuildMemberStore';
import RoleStore from '../../stores/RoleStore';
export default class Guild {
    id: string;
    Name: string;
    OwnerId: string;
    Region: string;
    AfkTimeout: number;
    VerificationLevel: number;
    DefaultMessageNotification: number;
    ExplicitContentFilter: number;
    Roles: RoleStore;
    Emojis: EmojiStore;
    Features: string[];
    MFALevel: number;
    MaxMembers: number;
    PremiumTier: number;
    PremiumSubscriptionCount: number | undefined;
    Banner: string | undefined;
    Description: string | undefined;
    VanityURLCode: string | undefined;
    MaxPresences: number | undefined;
    Presences: any[] | undefined;
    Channels: ChannelStore;
    Members: GuildMemberStore;
    VoiceStates: any[] | undefined;
    MemberCount: number | undefined;
    Unavailable: boolean | undefined;
    Large: boolean | undefined;
    JoinedAt: number | undefined;
    SystemChannelId: string | undefined;
    WidgetChannelId: string | undefined;
    WidgetEnabled: boolean | undefined;
    ApplicationId: string | undefined;
    EmbedChannelId: string | undefined;
    EmbedEnabled: boolean | undefined;
    AfkChannelId: string | undefined;
    Permissions: number | undefined;
    Owner: boolean | undefined;
    Icon: string | undefined;
    Splash: string | undefined;
    private Client;
    constructor(client: DiscordClient, GuildObject: IDiscordGuild);
    private ResolveRoles;
    private ResolveEmojis;
    private ResolveMembers;
    private ResolveChannels;
}
