declare const _default: {
    CHANNEL_CREATE: string;
    CHANNEL_DELETE: string;
    CHANNEL_PINS_UPDATE: string;
    CHANNEL_UPDATE: string;
    GUILD_BAN_ADD: string;
    GUILD_BAN_REMOVE: string;
    GUILD_CREATE: string;
    GUILD_DELETE: string;
    GUILD_EMOJIS_UPDATE: string;
    GUILD_INTEGRATIONS_UPDATE: string;
    GUILD_MEMBERS_CHUNK: string;
    GUILD_MEMBER_ADD: string;
    GUILD_MEMBER_REMOVE: string;
    GUILD_MEMBER_UPDATE: string;
    GUILD_ROLE_CREATE: string;
    GUILD_ROLE_DELETE: string;
    GUILD_ROLE_UPDATE: string;
    GUILD_UPDATE: string;
    INVALID_SESSION: string;
    MESSAGE_CREATE: string;
    MESSAGE_DELETE: string;
    MESSAGE_DELETE_BULK: string;
    MESSAGE_REACTION_ADD: string;
    MESSAGE_REACTION_REMOVE: string;
    MESSAGE_REACTION_REMOVE_ALL: string;
    MESSAGE_UPDATE: string;
    PRESENCE_UPDATE: string;
    READY: string;
    RESUMED: string;
    TYPING_START: string;
    USER_UPDATE: string;
    VOICE_SERVER_UPDATE: string;
    VOICE_STATE_UPDATE: string;
    WEBHOOKS_UPDATE: string;
};
export default _default;
