import { IDiscordGuild, IDiscordVoiceServerGatewayEvent } from '../../common/types';
import DiscordClient from '../../DiscordClient';
import ChannelStore from '../../stores/ChannelStore';
import EmojiStore from '../../stores/EmojiStore';
import GuildMemberStore from '../../stores/GuildMemberStore';
import PresenceStore from '../../stores/PresenceStore';
import RoleStore from '../../stores/RoleStore';
import VoiceStateStore from '../../stores/VoiceStateStore';
import VoiceConnection from '../../voice/VoiceConnection';
import VoiceManager from '../../voice/VoiceManager';
export default class Guild {
    id: string;
    Name: string;
    OwnerId: string;
    Region: string;
    AfkTimeout: number;
    VerificationLevel: number;
    DefaultMessageNotification: number;
    ExplicitContentFilter: number;
    Roles: RoleStore;
    Emojis: EmojiStore;
    Features: string[];
    MFALevel: number;
    MaxMembers: number;
    PremiumTier: number;
    VoiceConnection?: VoiceConnection;
    PendingVoiceConnection?: boolean;
    PendingVoiceServerDetails?: IDiscordVoiceServerGatewayEvent;
    PremiumSubscriptionCount: number | undefined;
    Banner: string | undefined;
    Description: string | undefined;
    VanityURLCode: string | undefined;
    MaxPresences: number | undefined;
    Presences: PresenceStore;
    Channels: ChannelStore;
    Members: GuildMemberStore;
    VoiceStates: VoiceStateStore;
    MemberCount: number | undefined;
    Unavailable: boolean | undefined;
    Large: boolean | undefined;
    JoinedAt: number | undefined;
    SystemChannelId: string | undefined;
    WidgetChannelId: string | undefined;
    WidgetEnabled: boolean | undefined;
    ApplicationId: string | undefined;
    EmbedChannelId: string | undefined;
    EmbedEnabled: boolean | undefined;
    AfkChannelId: string | undefined;
    Permissions: number | undefined;
    Owner: boolean | undefined;
    Icon: string | undefined;
    Splash: string | undefined;
    private readonly Client;
    constructor(client: DiscordClient, GuildObject: IDiscordGuild);
    CreateVoiceConnection(Token: string, Endpoint: string): Promise<VoiceManager>;
    private ResolveVoiceStates;
    private ResolvePresences;
    private ResolveRoles;
    private ResolveEmojis;
    private ResolveMembersAndPresences;
    private ResolveChannels;
}
